# Setup
title:               IFT6758 Blog A-09
tagline:             'Data science on NHL data'
description:         'Projet de science des données dans le cadre du cours IFT-6758 de UdeM. Le projet concerne les données de la LNH.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sebastian Cobuzzi, Mohamed Ali Mami, Olivier Couture, Rodrigo Flores Soto
  email:             sebastian.cobuzzi@umontreal.ca, mohamed.ali.mami@umontreal.ca, olivier.couture.1@umontreal.ca, rodrigo.alejandro.flores-soto@umontreal.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

